/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CgsAittribuleTag: typeof import('./src/components/CgsAittribuleTag.vue')['default']
    CgsCategory: typeof import('./src/components/CgsCategory.vue')['default']
    CgsColorTag: typeof import('./src/components/CgsColorTag.vue')['default']
    CgsFilter: typeof import('./src/components/CgsFilter.vue')['default']
    CgsHeader: typeof import('./src/components/CgsHeader.vue')['default']
    CustomImagePreview: typeof import('./src/components/CustomImagePreview.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonSourceMaterial: typeof import('./src/components/SkeletonSourceMaterial.vue')['default']
    SourceMaterial: typeof import('./src/components/SourceMaterial.vue')['default']
  }
}
